<a href="https://colab.research.google.com/github/avishek7713/Python-For-Data-Engineering/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# --------- CREATING ARRAYS ----------

import numpy as np

nums = [1,2,3,4,5]

array1 = np.array(nums)
print(array1)

[1 2 3 4 5]


In [6]:
zero_array = np.zeros(5) # GENERATING AN ARRAY OF 5 ZEROS
print(zero_array)

[0. 0. 0. 0. 0.]


In [7]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [8]:
range_array = np.arange(1, 10, 2) # array starting from 1 to 10 and step by 2
print(range_array)

[1 3 5 7 9]


In [12]:
random_array = np.random.randint(1, 100, 5) # GENERATE 5 RANDOM NUMBERS FROM 1 TO 100
print(random_array)

[37 71 47 15 48]


In [15]:
random_matrix = np.random.rand(3, 3) # GENERATIGN A 3 X 3 RANDOM MATRIX
print(random_matrix)

[[0.16187478 0.39773962 0.33108902]
 [0.44190533 0.04520563 0.31003287]
 [0.92846237 0.82051659 0.04629691]]


In [16]:
shape = range_array.shape # shape of the matrix
print(shape)

(5,)


In [17]:
size = range_array.size # size of the matrix
print(size)

5


In [20]:
dtype = random_matrix.dtype # datatype of the matrix
print(dtype)

float64


In [23]:
print(range_array.ndim) # dimension using NDIM()

1


In [24]:
# ________________ ARRAY OPERATIONS ________________

import numpy as np

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

sum = array1 + array2
sub = array1 - array2
mul = array1 * array2
div = array1 / array2
print(sum, sub, mul, div)

[ 7  9 11 13 15] [-5 -5 -5 -5 -5] [ 6 14 24 36 50] [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [29]:
# Aggregation Functions

mean = np.mean(array1)
print(mean)

sum = np.sum(array1)
print(sum)

max = np.max(array1)
print(max)

min = np.min(array1)
print(min)

3.0
15
5
1


In [31]:
# Boolean operations

greater_than_array = array1 > 3
print(greater_than_array)

[False False False  True  True]


In [32]:
# Broadcasting

result = array1 + 5 # broadcasting an element to all the elements in the array
print(result)

[ 6  7  8  9 10]


In [33]:
# ___________ Indexing and Slicing _________

import numpy as np

array1 = np.array([10, 20, 30, 40, 50])

secondElement = array1[1]
print(secondElement)

20


In [34]:
secondLastElement = array1[-2]
print(secondLastElement)

40


In [36]:
# Slicing

sliced_arr = array1[1:4] # printing elements from the second position to the fourth position
print(sliced_arr)

[20 30 40]


In [38]:
step_array = array1[::2] # print every second element
print(step_array)

[10 30 50]


In [39]:
# operations in the matrix

matrix = np.array (
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [40]:
element = matrix[1,1] # accessing a certain element in the matrix
print(element)

5


In [41]:
second_row = matrix[1, :] # printing the entire second row
print(second_row)

[4 5 6]


In [42]:
second_column = matrix[:, 1] # printing the second column
print(second_column)

[2 5 8]


In [43]:
# Missing data management

data = np.array(
    [1,2,3,np.nan,5]
)

missing = np.isnan(data) # finding the missing value
print(missing)

[False False False  True False]


In [47]:
data_fill = np.nan_to_num(data, nan = 0) # replacing the nan value with a value
print(data_fill)

[1. 2. 3. 0. 5.]


In [48]:
# ___________ Linear Algebra and Statistics ____________

import numpy as np

array1 = np.array([
    [1,2],
    [3,4]
])

array2 = np.array([
    [5, 6],
    [7,8]
])


In [49]:
mul = np.dot(array1, array2) # dot product or matrix multiplication using "MUL"
print(mul)

[[19 22]
 [43 50]]


In [50]:
inver = np.linalg.inv(array1) # inversion of the matrix using "linalg()"
print(inver)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [51]:
eval, evect = np.linalg.eig(array1) # eigen value and eigen vector
print(eval, evect)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [54]:
# Hypothesis testing

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)
print(mean, std)

3.0 1.4142135623730951


In [56]:
data1 = np.array([11,12,13,14,15])
corr = np.corrcoef(data, data1) # finding correlation between two arrays
print(corr)


[[1. 1.]
 [1. 1.]]


In [57]:
# Writing the numpy array into file

np.savetxt('output.csv', mul, delimiter= ",") # save as a text file

In [58]:
np.save("output.npy", mul) # saving as a numpy binary file, is faster

In [59]:
# for using - Load using "np.load()"

new_matrix = np.load("output.npy")
print(new_matrix)

[[19 22]
 [43 50]]


In [61]:
# save as excel

import pandas as pd

df = pd.DataFrame(mul)
df.to_excel("output.xlsx")